/* Criar o banco de dados */
CREATE DATABASE IF NOT EXISTS DB_COMBUSTON CHARACTER SET utf8 COLLATE utf8_general_ci;

/* Criando usuario de sistema */
CREATE USER 'ac_system'@'localhost' IDENTIFIED BY '12345@Flm';
GRANT INSERT ON DB_COMBUSTON . * TO 'ac_system'@'localhost';
GRANT SELECT ON DB_COMBUSTON . * TO 'ac_system'@'localhost';
GRANT UPDATE ON DB_COMBUSTON . * TO 'ac_system'@'localhost';
GRANT DELETE ON DB_COMBUSTON . * TO 'ac_system'@'localhost';

/* Reload permisões */
FLUSH PRIVILEGES;

/* Tabela dos usuarios */
CREATE TABLE IF NOT EXISTS T_USER (
    USER_CPF  BIGINT UNSIGNED ZEROFILL NOT NULL, #ID Usuario
    USER_NOME VARCHAR(60) NOT NULL, #Nome
    USER_PASS VARCHAR(100) NOT NULL, #Senha
    USER_STT  TINYINT(1) ZEROFILL NOT NULL DEFAULT 0, #Status
    PRIMARY KEY (USER_CPF)
);

INSERT INTO T_USER (USER_MAIL, USER_PASS, USER_CMOD, USER_CMAR, USER_NOME)
VALUES ('natashow@gmail.com', 'MTIzNDU=', 'Gol', 'Volkswagen', 'Natasha');
INSERT INTO T_USER (USER_MAIL, USER_PASS, USER_CMOD, USER_CMAR, USER_NOME)
VALUES ('felipe.lm@hotmail.com.br', 'MTIzNDU=', 'Gol', 'Volkswagen', 'Felipe');

/* Tabela dos postos */
CREATE TABLE IF NOT EXISTS T_GASTOS (
	GST_ID      BIGINT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT, #ID Gasto
    GST_USER    BIGINT UNSIGNED ZEROFILL NOT NULL, #ID User
    GST_POST    VARCHAR(60) NOT NULL, #Nome Posto
    GST_COMBS   VARCHAR(100), #Combustivel
    GST_LITRO   DECIMAL(4,2) NOT NULL DEFAULT '0.0', #Litros abastecido
    GST_VLR    	DECIMAL(5,2) NOT NULL DEFAULT '0.0', #Valor do abastecimento
    GST_DATA    DATE DEFAULT NOW(), #Data do abastecimento
    
    PRIMARY KEY (GST_ID),
    FOREIGN KEY (GST_USER) REFERENCES T_USER(USER_ID)
);

INSERT INTO T_GASTOS (GST_USER, GST_POST, GST_COMBS, GST_LITRO, GST_VLR)
VALUES (00000000000000000001, 'Posto Shell', 'Gasolina', '4.5', '33.5');
INSERT INTO T_GASTOS (GST_USER, GST_POST, GST_COMBS, GST_LITRO, GST_VLR)
VALUES (00000000000000000001, 'Posto Shell', 'Gasolina', '2.0', '10');

INSERT INTO T_POSTO (POSTO_NOME, POSTO_END )
VALUES ('Posto Shell 1', 'Av. Engenheiro Domingos Ferreira, 33');
INSERT INTO T_POSTO (POSTO_NOME, POSTO_END )
VALUES ('Posto Shell 2', 'Av. Conselheiro Aguiar, 105');
INSERT INTO T_POSTO (POSTO_NOME, POSTO_END )
VALUES ('Posto Ipiranga', 'Av. Alfredo Lisboa, 2044');

/* Tabela dos serviços */
CREATE TABLE IF NOT EXISTS T_POST (
	POST_ID      BIGINT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT, #ID Serviço
    POST_NOME    VARCHAR(60) NOT NULL, #Nome do posto
    POST_LAT     DECIMAL(10,7) NOT NULL, #Latitude
    POST_LONG    DECIMAL(10,7) NOT NULL, #Longitude
    
    PRIMARY KEY (POST_ID)
);

INSERT INTO T_POST (POST_NOME, POST_LAT, POST_LONG)
VALUES ('Posto Shell', '-3.7882544','-38.4996603');
INSERT INTO T_POST (POST_NOME, POST_LAT, POST_LONG)
VALUES ('Posto Petrobras', '-3.7882029','-38.501291');
INSERT INTO T_POST (POST_NOME, POST_LAT, POST_LONG)
VALUES ('Posto Petrobras', '-3.7875064','-38.5040343');

/* Tabela dos Posto serviço */
CREATE TABLE IF NOT EXISTS T_POST_SERV (
	POST_SERV_PID BIGINT UNSIGNED ZEROFILL NOT NULL, #ID Posto
    POST_SERV_SID BIGINT UNSIGNED ZEROFILL NOT NULL, #ID Serviço
    
    PRIMARY KEY (POST_SERV_PID, POST_SERV_SID)
);

INSERT INTO T_POST_SERV (POST_SERV_PID, POST_SERV_SID)
VALUES (3, 1);
INSERT INTO T_POST_SERV (POST_SERV_PID, POST_SERV_SID)
VALUES (3, 2);
INSERT INTO T_POST_SERV (POST_SERV_PID, POST_SERV_SID)
VALUES (2, 3);
INSERT INTO T_POST_SERV (POST_SERV_PID, POST_SERV_SID)
VALUES (1, 4);

delete from T_POST_SERV where POST_SERV_PID = 3;

/* Tabela dos usuarios */
CREATE TABLE IF NOT EXISTS T_CLIENT (
	CLIENT_ID      BIGINT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT, #ID Usuario
	CLIENT_NOME    VARCHAR(60) NOT NULL, #Nome do cliente
    CLIENT_END     VARCHAR(100), #Endereço
    
    PRIMARY KEY (CLIENT_ID)
);

INSERT INTO T_CLIENT (CLIENT_NOME, CLIENT_END)
VALUES ('João Marcos', 'Av. Rua dos bobos, 320');

/* Tabela dos historico do Posto */
CREATE TABLE IF NOT EXISTS T_HISTP (
	HISTP_ID      BIGINT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT, #ID Historico
    HISTP_POSTO   BIGINT UNSIGNED ZEROFILL NOT NULL, #ID cliente
    HISTP_CLIENT  BIGINT UNSIGNED ZEROFILL NOT NULL, #ID cliente
    HISTP_SERV    BIGINT UNSIGNED ZEROFILL NOT NULL, #ID Serviço
    HISTP_DATA    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, #Data
    HISTP_VLR     DECIMAL(10,2) UNSIGNED NOT NULL, # Valor
    
    PRIMARY KEY (HISTP_ID),
    FOREIGN KEY (HISTP_POSTO) REFERENCES T_POSTO(POSTO_ID),
    FOREIGN KEY (HISTP_CLIENT) REFERENCES T_CLIENT(CLIENT_ID),
    FOREIGN KEY (HISTP_SERV) REFERENCES T_SERV(SERV_ID)
);

INSERT INTO T_HISTP (HISTP_POSTO, HISTP_CLIENT, HISTP_SERV, HISTP_VLR)
VALUES (1, 1, 1, '100.5');
INSERT INTO T_HISTP (HISTP_POSTO, HISTP_CLIENT, HISTP_SERV, HISTP_VLR)
VALUES (1, 1, 4, '10.5');

/* Tabela dos historico do Posto */
CREATE TABLE IF NOT EXISTS T_HISTC (
	HISTC_ID      BIGINT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT, #ID Historico
    HISTC_CLIENT  BIGINT UNSIGNED ZEROFILL NOT NULL, #ID cliente
    HISTC_POSTO   BIGINT UNSIGNED ZEROFILL NOT NULL, #ID POSTO
    HISTC_SERV    BIGINT UNSIGNED ZEROFILL NOT NULL, #ID Serviço
    HISTC_DATA    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, #Data
    HISTC_VLR     DECIMAL(10,2) UNSIGNED NOT NULL, # Valor
    
    PRIMARY KEY (HISTC_ID),
    FOREIGN KEY (HISTC_CLIENT) REFERENCES T_CLIENT(CLIENT_ID),
    FOREIGN KEY (HISTC_POSTO) REFERENCES T_POSTO(POSTO_ID),
    FOREIGN KEY (HISTC_SERV) REFERENCES T_SERV(SERV_ID)
);

INSERT INTO T_HISTC (HISTC_CLIENT, HISTC_POSTO, HISTC_SERV, HISTC_VLR)
VALUES (1, 1, 4, '10.5');


SELECT * FROM T_USER;
SELECT * FROM T_GASTOS;
SELECT * FROM T_POST;
SELECT * FROM T_POST_SERV;

